name: Compiling-TeX
on:
  push:
    branches:
      - main
      - 02-ci-cv
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v1

    - name: Compile CV
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: tex

    - name: Check pdf files
      run: |
        file tex/main.pdf | grep -q ' PDF '
    
    - name: Upload with action-artifact
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: tex/main.pdf
      if: always()
